ghdl -a dregister_1.vhd
ghdl -a dregister_2.vhd
ghdl -a dregister.vhd
ghdl -a 16bit_adder.vhd
ghdl -a 16bit_sub.vhd
ghdl -a full_adder.vhd
ghdl -a subtractor.vhd
ghdl -a 16bit_nand.vhd
ghdl -a my_alu.vhd
ghdl -a rf_comp.vhdl
ghdl -a se7.vhd
ghdl -a se10.vhd
ghdl -a memory.vhd
ghdl -a priority_encoder.vhd
ghdl -a pipeline-bank.vhdl
ghdl -a decoder.vhd
ghdl -a prisc.vhd
ghdl -a comparator.vhd
